language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx

before_install:
 - if [ "$TRAVIS_OS_NAME" != "linux" ]; then
     brew update;
     brew uninstall jsoncpp;
     brew install jsoncpp;
   fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libjsoncpp-dev
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - make test
notifications:
  email:
    recipients:
      - dillo@nih.at,tk@giga.or.at
    on_success: change
    on_failure: change
